### ISSUE TITLE
实体编号疑问

### ISSUE THREAD

**Issue by MrRace** [beader/ruijin_round1#4]
在文件0.ann内容如下：
```
T1	Disease 1845 1850	1型糖尿病
T2	Disease 1983 1988	1型糖尿病
T4	Disease 30 35	2型糖尿病
T5	Disease 1822 1827	2型糖尿病
T6	Disease 2055 2060	2型糖尿病
T7	Disease 2324 2329	2型糖尿病
T8	Disease 4325 4330	2型糖尿病
T9	Disease 5223 5228	2型糖尿病
T10	Disease 5794 5799	2型糖尿病
T11	Disease 5842 5847	2型糖尿病
...
```
按照文中所述，第一列为实体编号，第二列为实体类别，第三列为实体位置信息。为啥“2型糖尿病“很多个实体编号？不都是同一个实体吗？所以，都是“2型糖尿病“编号的用途是啥？另外，好像有些编号是连续的，而有些是断裂的？比如为啥没有T3?直接到了T4?

**Comment by beader** [comment]
1. 不同位置的 `2型糖尿病`，看作不同的实体。以 T1 为例，表示文章中第 1845 ～ 1850 这 5 个字是一个 Disease 类型的实体，这 5 个字是 `1型糖尿病`。除此之外，由于上下文的不同，同样的文字可能在某个上下文环境中是一个 Disease，在另一个上下文中是一个 Side-Effect
2. 这里的 T1, T2，是实体的 ID，仅仅作为一个标识，没有顺序性与连续性。缺少 T3 可能是由于主办方在数据处理环节删除了
