### ISSUE TITLE
jupyter中如何显示  brat

### ISSUE THREAD

**Issue by jiangzhonglian** [beader/ruijin_round1#6]
我这边一直报错，请问小哥哥是怎么做到的？
![image](https://user-images.githubusercontent.com/9199175/58236662-f1a0be80-7d75-11e9-9c55-3437105885bb.png)

**Comment by beader** [comment]
这个是 `spacy` 包的一个功能，你先去安装一下 [spacy](https://spacy.io/)

我是用了 `spacy` 中的 `displacy.render` 来把标签渲染成 html。至于 jupyter 里面怎么把 html 渲染出来，可以手动去实现一个类的 `_repr_html_` 方法，这个是 jupyter 特有的功能，详细可以参考这里
[data_utils.py#L54](https://github.com/beader/ruijin_round1/blob/050039dc9560430e063c0b898a9c88ad15a142ea/data_utils/data_utils.py#L54)

**Comment by jiangzhonglian** [comment]
非常感谢🙏

**Comment by jiangzhonglian** [comment]
我测试了一下小哥哥的代码，依然报错

![image](https://user-images.githubusercontent.com/9199175/58241982-8c05ff80-7d80-11e9-8e2a-7a61bfd3cbd2.png)

**Comment by beader** [comment]
帮你查了一下，这是 `spacy` 的一个 bug [Displacy producing KeyError: 'settings' #3531](https://github.com/explosion/spaCy/issues/3531)

你 pull  一下 [fix-displacy-keyrror-bug](https://github.com/beader/ruijin_round1/tree/fix-displacy-keyrror-bug) 这个分支，看看问题解决了没有

**Comment by jiangzhonglian** [comment]
问题解决了，非常谢谢小哥哥
